// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "player":return img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f f f c c f f f c . 
f f f c f f f f f f f c . 
c c c f f f e e f f c c . 
f f f f f e e f f c c f . 
f f f b f e e f b f f f . 
. f 4 1 f 4 4 f 1 4 f . . 
. f e 4 4 4 4 4 4 e f . . 
. f f f e e e e f f f . . 
f e f b 7 7 7 7 b f e f . 
e 4 f 7 7 7 7 7 7 f 4 e . 
e e f 6 6 6 6 6 6 f e e . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`;
            case "image2":
            case "Santa":return img`
......1111......................
....fff11fff....................
...fff2222fff...................
..fffeeeeeefff..................
..ffe222222eef..................
..fe2ffffff2ef.......ee.........
..ffffeeeeffff....eeeeee........
.ffefbf44fbfeff.eeeeeeeee.......
.fee41fddf14eefeeeeeeeeeeee.....
..feeddddddeefeee77277eeeeee....
...feddddddefeeee77277eeeeeee...
..e4fddddddf4e.ee22222eeeeeeee..
..4df222222fd4..e7727eeeeeeeee..
..44f445544f44.ee772eeeeeeeeee..
.....ffffff....eeeeeeeeeeeeeee..
.....ff..ff....eeeeeeeeeeeeeee..
...............eeeeeeeeeeeeee...
................eeeeeeeeeeeee...
.................eeeeeeeeeeee...
..................eeeeeeeeee....
...................eeeeeeee.....
.......................eee......
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
